name: Publish to site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Render Markdown
      uses: ZacJW/markdown-html-action@1.1.0
      with:
        input_files: '[["body.md"]]'
        output_files: '["body.html"]'
        extensions: '["extra", "smarty"]'
    
    - name: Publish to site
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: ""
        remoteDir: "httpdocs"
        options: "--delete --asci --verbose"


#    - name: Validate composer.json and composer.lock
#      run: composer validate --strict


